from .student import Student
from .schedule import ScheduleMeeting, ScheduleBlock, ClassInfo, LEGACY_DEFAULT_COLLEGE
from .config import RosterConfig
from .recipe import (
    RECIPE_SCHEMA_VERSION,
    TemplateError,
    AmbiguousTemplateError,
    InvalidRecipeError,
    RosterBinding,
    HeaderCellBinding,
    SignatureBinding,
    GeneratorProfile,
    PROFILE_ACADEMIC_DOCX,
    PROFILE_GRADE_SHEET_XLSX,
    PROFILE_CUSTOM_DOCX,
    PROFILE_REGISTRY,
    RawTemplateRecipeCandidate,
    ValidatedTemplateRecipe,
)
from .template_set import (
    CANONICAL_ROLES,
    ACADEMIC_CEIT_ROLES,
    ATTENDANCE_ROLES,
    GRADE_SHEET_ROLES,
    ROLE_PROFILE_MAPPING,
    ROLE_DISPLAY_NAMES,
    TemplateSetError,
    InvalidTemplateSetError,
    MissingTemplateRoleError,
    TemplateEntry,
    TemplateSet,
)

__all__ = [
    "Student",
    "ScheduleMeeting",
    "ScheduleBlock",
    "ClassInfo",
    "LEGACY_DEFAULT_COLLEGE",
    "RosterConfig",
    "RECIPE_SCHEMA_VERSION",
    "TemplateError",
    "AmbiguousTemplateError",
    "InvalidRecipeError",
    "RosterBinding",
    "HeaderCellBinding",
    "SignatureBinding",
    "GeneratorProfile",
    "PROFILE_ACADEMIC_DOCX",
    "PROFILE_GRADE_SHEET_XLSX",
    "PROFILE_CUSTOM_DOCX",
    "PROFILE_REGISTRY",
    "RawTemplateRecipeCandidate",
    "ValidatedTemplateRecipe",
    "CANONICAL_ROLES",
    "ACADEMIC_CEIT_ROLES",
    "ATTENDANCE_ROLES",
    "GRADE_SHEET_ROLES",
    "ROLE_PROFILE_MAPPING",
    "ROLE_DISPLAY_NAMES",
    "TemplateSetError",
    "InvalidTemplateSetError",
    "MissingTemplateRoleError",
    "TemplateEntry",
    "TemplateSet",
]

